name: Release
on:
  push:
    branches: [master]

permissions:
  contents: write # Required for creating releases
  issues: write # Required for creating issues
  pull-requests: write # Required for creating PRs
  packages: write # If publishing to GitHub Packages

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build
        run: nix build -L

      - name: Create archive
        run: |
          mkdir -p dist
          cp result/bin/fusion-installer-rs dist/
          cd dist
          tar -czf fusion-installer-rs-universal-macos.tar.gz fusion-installer-rs
          shasum -a 256 fusion-installer-rs-universal-macos.tar.gz > fusion-installer-rs-universal-macos.tar.gz.sha256
          cd ..

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
